language: objective-c
osx_image: xcode11

branches:
  only:
  - master

script:
  - xcodebuild -project PinFieldView.xcodeproj -scheme PinFieldView -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro' build
  - pod lib lint --quick
